//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(HardwareBackend)
		**out = **in
	}
	if in.Simulator != nil {
		in, out := &in.Simulator, &out.Simulator
		*out = new(SimulatorBackend)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSpec.
func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]v1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareBackend) DeepCopyInto(out *HardwareBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareBackend.
func (in *HardwareBackend) DeepCopy() *HardwareBackend {
	if in == nil {
		return nil
	}
	out := new(HardwareBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckSpec) DeepCopyInto(out *HealthCheckSpec) {
	*out = *in
	out.Interval = in.Interval
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckSpec.
func (in *HealthCheckSpec) DeepCopy() *HealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(HealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSpec) DeepCopyInto(out *NatsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSpec.
func (in *NatsSpec) DeepCopy() *NatsSpec {
	if in == nil {
		return nil
	}
	out := new(NatsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulatorBackend) DeepCopyInto(out *SimulatorBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulatorBackend.
func (in *SimulatorBackend) DeepCopy() *SimulatorBackend {
	if in == nil {
		return nil
	}
	out := new(SimulatorBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Z21Device) DeepCopyInto(out *Z21Device) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Z21Device.
func (in *Z21Device) DeepCopy() *Z21Device {
	if in == nil {
		return nil
	}
	out := new(Z21Device)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Z21Device) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Z21DeviceList) DeepCopyInto(out *Z21DeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Z21Device, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Z21DeviceList.
func (in *Z21DeviceList) DeepCopy() *Z21DeviceList {
	if in == nil {
		return nil
	}
	out := new(Z21DeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Z21DeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Z21DeviceSpec) DeepCopyInto(out *Z21DeviceSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	out.NATS = in.NATS
	out.HealthCheck = in.HealthCheck
	in.Gateway.DeepCopyInto(&out.Gateway)
	if in.BroadcastFlags != nil {
		in, out := &in.BroadcastFlags, &out.BroadcastFlags
		*out = new(uint32)
		**out = **in
	}
	if in.CANAddressPoolRef != nil {
		in, out := &in.CANAddressPoolRef, &out.CANAddressPoolRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Z21DeviceSpec.
func (in *Z21DeviceSpec) DeepCopy() *Z21DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(Z21DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Z21DeviceStatus) DeepCopyInto(out *Z21DeviceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSuccessfulHealthCheck != nil {
		in, out := &in.LastSuccessfulHealthCheck, &out.LastSuccessfulHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.LockCode != nil {
		in, out := &in.LockCode, &out.LockCode
		*out = new(uint8)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Z21DeviceStatus.
func (in *Z21DeviceStatus) DeepCopy() *Z21DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(Z21DeviceStatus)
	in.DeepCopyInto(out)
	return out
}
