//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Simulation) DeepCopyInto(out *Simulation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Simulation.
func (in *Simulation) DeepCopy() *Simulation {
	if in == nil {
		return nil
	}
	out := new(Simulation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Simulation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulationCANBooster) DeepCopyInto(out *SimulationCANBooster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulationCANBooster.
func (in *SimulationCANBooster) DeepCopy() *SimulationCANBooster {
	if in == nil {
		return nil
	}
	out := new(SimulationCANBooster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulationCANDetector) DeepCopyInto(out *SimulationCANDetector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulationCANDetector.
func (in *SimulationCANDetector) DeepCopy() *SimulationCANDetector {
	if in == nil {
		return nil
	}
	out := new(SimulationCANDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulationList) DeepCopyInto(out *SimulationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Simulation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulationList.
func (in *SimulationList) DeepCopy() *SimulationList {
	if in == nil {
		return nil
	}
	out := new(SimulationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimulationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulationSpec) DeepCopyInto(out *SimulationSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.CANDetectors != nil {
		in, out := &in.CANDetectors, &out.CANDetectors
		*out = make([]SimulationCANDetector, len(*in))
		copy(*out, *in)
	}
	if in.CANBoosters != nil {
		in, out := &in.CANBoosters, &out.CANBoosters
		*out = make([]SimulationCANBooster, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulationSpec.
func (in *SimulationSpec) DeepCopy() *SimulationSpec {
	if in == nil {
		return nil
	}
	out := new(SimulationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulationStatus) DeepCopyInto(out *SimulationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulationStatus.
func (in *SimulationStatus) DeepCopy() *SimulationStatus {
	if in == nil {
		return nil
	}
	out := new(SimulationStatus)
	in.DeepCopyInto(out)
	return out
}
