apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elp-api
  labels:
    app.kubernetes.io/name: elp-api
rules:
  - apiGroups:
      - z21.trains.io
    resources:
      - z21devices
      - simulations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
