apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elp-api
  labels:
    app.kubernetes.io/name: elp-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elp-api
subjects:
  - kind: ServiceAccount
    name: elp-api
    namespace: default
