// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulatorService_BroadcastSystemState_FullMethodName    = "/trains.io.z21sim.control.v1.SimulatorService/BroadcastSystemState"
	SimulatorService_SetTrackPower_FullMethodName           = "/trains.io.z21sim.control.v1.SimulatorService/SetTrackPower"
	SimulatorService_NotifyCANDeviceDetected_FullMethodName = "/trains.io.z21sim.control.v1.SimulatorService/NotifyCANDeviceDetected"
)

// SimulatorServiceClient is the client API for SimulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SimulatorService is the gRPC control plane for z21-sim.
// A sidecar (z21-sim-controller) uses it to inject unsolicited Z21 LAN events.
type SimulatorServiceClient interface {
	// BroadcastSystemState emits LAN_SYSTEMSTATE_DATACHANGED to subscribed clients.
	BroadcastSystemState(ctx context.Context, in *BroadcastSystemStateRequest, opts ...grpc.CallOption) (*BroadcastSystemStateResponse, error)
	// SetTrackPower updates simulator track power and emits unsolicited XpressNet
	// and system-state broadcasts to subscribed clients.
	SetTrackPower(ctx context.Context, in *SetTrackPowerRequest, opts ...grpc.CallOption) (*SetTrackPowerResponse, error)
	// NotifyCANDeviceDetected registers a CAN device and broadcasts its initial
	// status to subscribed clients, emulating hot-plug detection.
	NotifyCANDeviceDetected(ctx context.Context, in *NotifyCANDeviceDetectedRequest, opts ...grpc.CallOption) (*NotifyCANDeviceDetectedResponse, error)
}

type simulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulatorServiceClient(cc grpc.ClientConnInterface) SimulatorServiceClient {
	return &simulatorServiceClient{cc}
}

func (c *simulatorServiceClient) BroadcastSystemState(ctx context.Context, in *BroadcastSystemStateRequest, opts ...grpc.CallOption) (*BroadcastSystemStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastSystemStateResponse)
	err := c.cc.Invoke(ctx, SimulatorService_BroadcastSystemState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) SetTrackPower(ctx context.Context, in *SetTrackPowerRequest, opts ...grpc.CallOption) (*SetTrackPowerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTrackPowerResponse)
	err := c.cc.Invoke(ctx, SimulatorService_SetTrackPower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) NotifyCANDeviceDetected(ctx context.Context, in *NotifyCANDeviceDetectedRequest, opts ...grpc.CallOption) (*NotifyCANDeviceDetectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyCANDeviceDetectedResponse)
	err := c.cc.Invoke(ctx, SimulatorService_NotifyCANDeviceDetected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulatorServiceServer is the server API for SimulatorService service.
// All implementations must embed UnimplementedSimulatorServiceServer
// for forward compatibility.
//
// SimulatorService is the gRPC control plane for z21-sim.
// A sidecar (z21-sim-controller) uses it to inject unsolicited Z21 LAN events.
type SimulatorServiceServer interface {
	// BroadcastSystemState emits LAN_SYSTEMSTATE_DATACHANGED to subscribed clients.
	BroadcastSystemState(context.Context, *BroadcastSystemStateRequest) (*BroadcastSystemStateResponse, error)
	// SetTrackPower updates simulator track power and emits unsolicited XpressNet
	// and system-state broadcasts to subscribed clients.
	SetTrackPower(context.Context, *SetTrackPowerRequest) (*SetTrackPowerResponse, error)
	// NotifyCANDeviceDetected registers a CAN device and broadcasts its initial
	// status to subscribed clients, emulating hot-plug detection.
	NotifyCANDeviceDetected(context.Context, *NotifyCANDeviceDetectedRequest) (*NotifyCANDeviceDetectedResponse, error)
	mustEmbedUnimplementedSimulatorServiceServer()
}

// UnimplementedSimulatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulatorServiceServer struct{}

func (UnimplementedSimulatorServiceServer) BroadcastSystemState(context.Context, *BroadcastSystemStateRequest) (*BroadcastSystemStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastSystemState not implemented")
}
func (UnimplementedSimulatorServiceServer) SetTrackPower(context.Context, *SetTrackPowerRequest) (*SetTrackPowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTrackPower not implemented")
}
func (UnimplementedSimulatorServiceServer) NotifyCANDeviceDetected(context.Context, *NotifyCANDeviceDetectedRequest) (*NotifyCANDeviceDetectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyCANDeviceDetected not implemented")
}
func (UnimplementedSimulatorServiceServer) mustEmbedUnimplementedSimulatorServiceServer() {}
func (UnimplementedSimulatorServiceServer) testEmbeddedByValue()                          {}

// UnsafeSimulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulatorServiceServer will
// result in compilation errors.
type UnsafeSimulatorServiceServer interface {
	mustEmbedUnimplementedSimulatorServiceServer()
}

func RegisterSimulatorServiceServer(s grpc.ServiceRegistrar, srv SimulatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedSimulatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulatorService_ServiceDesc, srv)
}

func _SimulatorService_BroadcastSystemState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastSystemStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).BroadcastSystemState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_BroadcastSystemState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).BroadcastSystemState(ctx, req.(*BroadcastSystemStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_SetTrackPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTrackPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).SetTrackPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_SetTrackPower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).SetTrackPower(ctx, req.(*SetTrackPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_NotifyCANDeviceDetected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyCANDeviceDetectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).NotifyCANDeviceDetected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_NotifyCANDeviceDetected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).NotifyCANDeviceDetected(ctx, req.(*NotifyCANDeviceDetectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulatorService_ServiceDesc is the grpc.ServiceDesc for SimulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trains.io.z21sim.control.v1.SimulatorService",
	HandlerType: (*SimulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastSystemState",
			Handler:    _SimulatorService_BroadcastSystemState_Handler,
		},
		{
			MethodName: "SetTrackPower",
			Handler:    _SimulatorService_SetTrackPower_Handler,
		},
		{
			MethodName: "NotifyCANDeviceDetected",
			Handler:    _SimulatorService_NotifyCANDeviceDetected_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/control/v1/control.proto",
}
